version: '3.8'

services:
  ai-faq-generator:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped 